# Generated by Django 4.0.4 on 2022-05-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sci_name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('img_url', models.URLField(max_length=512)),
                ('water_freq', models.CharField(max_length=50)),
                ('water_qty', models.CharField(blank=True, max_length=50)),
                ('light_level', models.CharField(blank=True, max_length=50)),
                ('temp', models.CharField(blank=True, max_length=50)),
                ('humidity', models.CharField(blank=True, max_length=50)),
                ('fertilizer_type', models.CharField(blank=True, max_length=256)),
                ('fertilizer_freq', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=1024)),
                ('profile_img', models.CharField(max_length=512)),
                ('pref_day1', models.CharField(max_length=50)),
                ('pref_day2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('img_url', models.URLField(max_length=512)),
                ('light_level', models.CharField(blank=True, max_length=50)),
                ('temp', models.CharField(blank=True, max_length=50)),
                ('humidity', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='greenthumb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Houseplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField()),
                ('loc_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='greenthumb.location')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenthumb.plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenthumb.user')),
            ],
        ),
    ]
