# Generated by Django 4.0.4 on 2022-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='img_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, default='Needs description', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity',
            field=models.CharField(blank=True, default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='img_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sci_name',
            field=models.CharField(blank=True, default='Not recorded', max_length=512),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_qty',
            field=models.CharField(blank=True, default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pref_day2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
